# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.dual_type import DualType  # noqa: F401,E501
from swagger_server import util


class EdgeData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, source: DualType=None, target: DualType=None, key: DualType=None, weight: float=None):  # noqa: E501
        """EdgeData - a model defined in Swagger

        :param source: The source of this EdgeData.  # noqa: E501
        :type source: DualType
        :param target: The target of this EdgeData.  # noqa: E501
        :type target: DualType
        :param key: The key of this EdgeData.  # noqa: E501
        :type key: DualType
        :param weight: The weight of this EdgeData.  # noqa: E501
        :type weight: float
        """
        self.swagger_types = {
            'source': DualType,
            'target': DualType,
            'key': DualType,
            'weight': float
        }

        self.attribute_map = {
            'source': 'source',
            'target': 'target',
            'key': 'key',
            'weight': 'weight'
        }
        self._source = source
        self._target = target
        self._key = key
        self._weight = weight

    @classmethod
    def from_dict(cls, dikt) -> 'EdgeData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Edge_data of this EdgeData.  # noqa: E501
        :rtype: EdgeData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source(self) -> DualType:
        """Gets the source of this EdgeData.


        :return: The source of this EdgeData.
        :rtype: DualType
        """
        return self._source

    @source.setter
    def source(self, source: DualType):
        """Sets the source of this EdgeData.


        :param source: The source of this EdgeData.
        :type source: DualType
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def target(self) -> DualType:
        """Gets the target of this EdgeData.


        :return: The target of this EdgeData.
        :rtype: DualType
        """
        return self._target

    @target.setter
    def target(self, target: DualType):
        """Sets the target of this EdgeData.


        :param target: The target of this EdgeData.
        :type target: DualType
        """
        if target is None:
            raise ValueError("Invalid value for `target`, must not be `None`")  # noqa: E501

        self._target = target

    @property
    def key(self) -> DualType:
        """Gets the key of this EdgeData.


        :return: The key of this EdgeData.
        :rtype: DualType
        """
        return self._key

    @key.setter
    def key(self, key: DualType):
        """Sets the key of this EdgeData.


        :param key: The key of this EdgeData.
        :type key: DualType
        """

        self._key = key

    @property
    def weight(self) -> float:
        """Gets the weight of this EdgeData.


        :return: The weight of this EdgeData.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight: float):
        """Sets the weight of this EdgeData.


        :param weight: The weight of this EdgeData.
        :type weight: float
        """

        self._weight = weight
