# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.edge_data import EdgeData  # noqa: F401,E501
from swagger_server import util


class Edge(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: EdgeData=None):  # noqa: E501
        """Edge - a model defined in Swagger

        :param data: The data of this Edge.  # noqa: E501
        :type data: EdgeData
        """
        self.swagger_types = {
            'data': EdgeData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Edge':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Edge of this Edge.  # noqa: E501
        :rtype: Edge
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> EdgeData:
        """Gets the data of this Edge.


        :return: The data of this Edge.
        :rtype: EdgeData
        """
        return self._data

    @data.setter
    def data(self, data: EdgeData):
        """Sets the data of this Edge.


        :param data: The data of this Edge.
        :type data: EdgeData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
