# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NodeData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, value: object=None, name: str=None):  # noqa: E501
        """NodeData - a model defined in Swagger

        :param id: The id of this NodeData.  # noqa: E501
        :type id: str
        :param value: The value of this NodeData.  # noqa: E501
        :type value: object
        :param name: The name of this NodeData.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'id': str,
            'value': object,
            'name': str
        }

        self.attribute_map = {
            'id': 'id',
            'value': 'value',
            'name': 'name'
        }
        self._id = id
        self._value = value
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'NodeData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Node_data of this NodeData.  # noqa: E501
        :rtype: NodeData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this NodeData.


        :return: The id of this NodeData.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this NodeData.


        :param id: The id of this NodeData.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def value(self) -> object:
        """Gets the value of this NodeData.


        :return: The value of this NodeData.
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value: object):
        """Sets the value of this NodeData.


        :param value: The value of this NodeData.
        :type value: object
        """

        self._value = value

    @property
    def name(self) -> str:
        """Gets the name of this NodeData.


        :return: The name of this NodeData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this NodeData.


        :param name: The name of this NodeData.
        :type name: str
        """

        self._name = name
